### ISSUE TITLE
Unable to run on docker - windows

### ISSUE THREAD

**Issue by uzair-sarwar** [tum-gis/cesium-terrain-builder-docker#10]
Docker container runs successfully 
But unable to find terrain tile. I used following commands on command prompt:
docker run --rm -it --name ctb -v //d/docker/terrain:/data tumgis/ctb-quantized-mesh

ctb-tile -f Mesh -C -N -o terrain dsm.tif

Following error is given:
ERROR 4: dsm.tif: No such file or directory
Error: could not open GDAL dataset

i've tried many ways to give paths. Please help.

**Comment by BWibo** [comment]
* Here are some examples for mounting docker volumes on windows. 
  https://stackoverflow.com/questions/45972812/are-you-trying-to-mount-a-directory-onto-a-file-or-vice-versa/63658451#63658451

* This may also depend on what system you are using:
  Are you running Docker on WSL 1 or WSL2? I am using WSL 2 and this works for me:

  ```
  docker run --rm -it --name ctb \
    -v /d/my/host/dir/with/data:/data \
    tumgis/ctb-quantized-mesh
  ``` 

* Here is the Docker volume docs: https://docs.docker.com/storage/volumes/

* Make sure that the path in the container is correct too. Check you current working directory with `pwd` and list file using `ls`.

Closing, as this is a Docker issue and not an issue of this image.
