### ISSUE TITLE
How to resume tiling terrain after stopping

### ISSUE THREAD

**Issue by predictwise** [tum-gis/cesium-terrain-builder-docker#11]
Hi @BWibo,

I am tiling a slightly large area with 77 `.tif` files (around 70GB). However, the power in the lab was out yesterday and hence led to shutting down the tiling at the level 18.

The current terrain tiles at level 18 have 4500+ `.terrain` files and I am sure it has not been finished yet. So, is it possible to resume the tiling instead of starting it from scratch again? Because it has already taken more than 30 hours to get these `.terrain` files at level 18.

Looking forward to your reply and thanks in advance!

Oliver

**Comment by BWibo** [comment]
According to [this](https://github.com/geo-data/cesium-terrain-builder#command-line-tools), `ctb-tile` comes with a resume option (`-R`). Please report if this is working for you.
Closing, as this is an issue of `ctb-tile` and not the Docker image maintained in this repo.

**Comment by predictwise** [comment]
Thank you very much. I will try it and report the result when facing the same problem.
