### ISSUE TITLE
How to view the results in Cesium?

### ISSUE THREAD

**Issue by ruanqizhen** [tum-gis/cesium-terrain-builder-docker#14]
I successfully created a bunch of .terrain files.  But I still don't know how to view them in Cesium.  Could anyone share me some documents or examples of using the results generated by the tool?

**Comment by BWibo** [comment]
This is done using the [CesiumTerrainProvider](https://cesium.com/learn/cesiumjs/ref-doc/CesiumTerrainProvider.html).
You need to host the created tiles on a specially configured webserver (gzip encoding support, see this [example](https://github.com/geo-data/cesium-terrain-server#caching-tiles-with-memcached)) or use [CesiumTerrainServer](https://github.com/geo-data/cesium-terrain-server).
Closing, as this is not directly related to the Docker images provided here.

**Comment by ruanqizhen** [comment]
Thank you so much!
