### ISSUE TITLE
quantized-mesh tiles are no “metadata” extension

### ISSUE THREAD

**Issue by zhangiser** [tum-gis/cesium-terrain-builder-docker#16]
I used this cmd in windows to produced terrain tiles
>ctb-tile -o D:\dem\globe d:\dem\world-16bit.tif -f Mesh -s 10 -e 0

but when load by cesiumJS ,i found a problem,there is no  “metadata” extension in 0/0/0.terrain and 0/1/0.terrrain.And the "metadata" is very important for cesiumJS to create quadtree,so it's absolutely need  “metadata” extension in level0 and level10.We can see the code at [https://github.com/CesiumGS/cesium/blob/7d7c5d06e712e71b7002f70100da8689080a3144/Source/Core/CesiumTerrainProvider.js#L308-L354](url)
When i searched this problem at cesium community,i also found a similar post:[https://community.cesium.com/t/terrain-loading-failed-in-ctb-production/14161](url)

Cesium for Unreal and CeisumJS currently requires that tile availability be attached to quantized-mesh tiles using the “metadata” extension.

So what should i do To add the “metadata” ?

Thanks!

**Comment by BWibo** [comment]
Hey there,
this is the repo of the Docker image for CesiumTerrainBuilder. Closing, as I cannot provide support for questions regarding the main application. The main repo can be found here: https://github.com/geo-data/cesium-terrain-builder
