### ISSUE TITLE
why cesium can not display globe?

### ISSUE THREAD

**Issue by Brilliant-orange** [tum-gis/cesium-terrain-builder-docker#24]
There was a problem loading the terrain in cesium. The cesium globe displays normally after removing the terrain.
In cesium1.96, chrome displays the following error:
Cesium.js:85 An error occurred in "Py": Failed to obtain terrain tile X: 0 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 8894653434"
Cesium.js:85 An error occurred in "Py": Failed to obtain terrain tile X: 1 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 2017542741"

cesium code like this:
	var terrainProvider1=new Cesium.CesiumTerrainProvider({
		url:"http://localhost:9000/"
	});
    const viewer = new Cesium.Viewer("cesiumContainer", {
      baseLayerPicker: false, 
      imageryProvider: imageryProvider,
      terrainProvider:terrainProvider1
      });
    viewer.scene.globe.enableLighting=true;

However, in the latest cesium, chrome does not output any errors and just does not display the globe.
How can I solve this problem? @BWibo @Son-HNguyen @TatjanaKutzner @thomashkolbe

**Comment by BWibo** [comment]
Hey there, this is the repo of the terrain builder docker image. I cannot provide support for general cesium questions.
Closing. Feel free to re-open if you have a question specific to this project.

**Comment by NataliaMedrano** [comment]
> There was a problem loading the terrain in cesium. The cesium globe displays normally after removing the terrain. In cesium1.96, chrome displays the following error: Cesium.js:85 An error occurred in "Py": Failed to obtain terrain tile X: 0 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 8894653434" Cesium.js:85 An error occurred in "Py": Failed to obtain terrain tile X: 1 Y: 0 Level: 0. Error message: "RangeError: Invalid typed array length: 2017542741"
> 
> cesium code like this: var terrainProvider1=new Cesium.CesiumTerrainProvider({ url:"http://localhost:9000/" }); const viewer = new Cesium.Viewer("cesiumContainer", { baseLayerPicker: false, imageryProvider: imageryProvider, terrainProvider:terrainProvider1 }); viewer.scene.globe.enableLighting=true;
> 
> However, in the latest cesium, chrome does not output any errors and just does not display the globe. How can I solve this problem? [@BWibo](https://github.com/BWibo) [@Son-HNguyen](https://github.com/Son-HNguyen) [@TatjanaKutzner](https://github.com/TatjanaKutzner) [@thomashkolbe](https://github.com/thomashkolbe)

Hello, have you manage to fix this issue?
