### ISSUE TITLE
Terrain pyramid getting created outside of dataset bounds

### ISSUE THREAD

**Issue by AgPriyanshu** [tum-gis/cesium-terrain-builder-docker#25]
Hi, I have facing this problem where a pyramid terrain is getting created outside of dataset bounds. Any idea why this could be happening. I have attached the screenshot of the terrain loaded in cesium
![image](https://github.com/tum-gis/cesium-terrain-builder-docker/assets/44399542/2d03d6a4-aa84-49b9-bd85-79992b994b3c)

**Comment by BWibo** [comment]
I recall having a similar issue with input data containing NO-DATA values. CTB does not support handling NO-DATA values in raster DEMs (see [here](https://github.com/geo-data/cesium-terrain-builder#limitations-and-todo)). I recommend getting rid of those e.g. using interpolation or setting them to a fixed value on the input data. Then try CTB  on the the edited data.

Closing, as this not an issue of the Docker image, but CTB itself or the input data.
