### ISSUE TITLE
Normals not working/missing

### ISSUE THREAD

**Issue by sambrooks-atkins** [tum-gis/cesium-terrain-builder-docker#4]
Hello,

I have generated some quantized mesh terrain files from a GeoTIFF using this repository, thank you very much for the only codebase that just plain works for making these for Cesium!

That being said, even though the terrain files work brilliantly in every other aspect, Cesium doesn't seem to think the normals were generated, despite the fact that I used the -N flag when creating the terrain files, and I have "requestVertexNormals: true" when creating the CesiumTerrainProvider that uses these files.

`viewer.terrainProvider.hasVertexNormals` returns false, and this code renders the terrain all the same shade of grey (for SlopeRamp) or black (for AspectRamp):

```
material = Cesium.Material.fromType('SlopeRamp');
globe.material = material;

material = Cesium.Material.fromType('AspectRamp');
globe.material = material;
```

I may be doing something wrong, but as I have no other way to check that the normals were correctly generated other than trying to use them in Cesium itself, I'm not sure how to double check that the normals are really there.

**Comment by BWibo** [comment]
Hey there, 
thank you, I am happy to hear the image was helpful for you!
Can you please post the commands you used for creating the terrain tileset?

Check out [this repo](https://github.com/heremaps/quantized-mesh-viewer). The tool provided there has some options for debugging terrains, including visualizing normals. 

Closing, as I cannot provide support for Cesium. I am just maintaining this Docker image here. Please re-post this issue where it belongs.

**Comment by sambrooks-atkins** [comment]
Thanks for the quick reply. I used the commands as specified in the readme, with the world.tif file in the [world.zip](https://github.com/tum-gis/cesium-terrain-builder-docker/files/3165430/world.zip) file attached (as an example, since I can't share my company's private GeoTIFFs):

```
ctb-tile -f Mesh -C -N -o terrain world.tif
ctb-tile -f Mesh -C -N -l -o terrain world.tif
```

The terrain files seem to work fine in Cesium, but do not show up at all in quantized-mesh-viewer (the repo you linked). I can't post an issue on the fork that your docker image is based on, and the original repo that was forked doesn't generate quantized mesh files, so it'd be no use asking them. I've tried with many different GeoTIFF files from many different sources, but none of them produce (with the above commands) terrain files which can be inspected with the quantized-mesh-viewer.

Since both the quantized-mesh-viewer and Cesium are having problems with the output of this docker image, and the fork it's based on does not accept issues, I'm not sure where else I can post this issue or ask these questions, as this seems like it could be a problem with this docker image and the code it contains.

If you have seen output from this docker image show up in the quantized-mesh-viewer repo's app, could you please provide the source file and the commands you used to create the terrain output? Thanks!

**Comment by sambrooks-atkins** [comment]
Here are some of the example .terrain files that gets output for the world.tif file attached above, and do not show up in the quantized mesh viewer: 
[6.zip](https://github.com/tum-gis/cesium-terrain-builder-docker/files/3165455/6.zip)

**Comment by BWibo** [comment]
Your example input data does not contain elevation values. I am seeing grayscale values from 0 to 255 on band 0. Check if your input data matches the input data description provided [here](https://github.com/ahuarte47/cesium-terrain-builder/tree/master-quantized-mesh#command-line-tools).

Probably, this pull request is where this issue belongs: geo-data/cesium-terrain-builder#64

**Comment by sambrooks-atkins** [comment]
You're right, the world.tif file I gave above is not a proper DEM geotiff - I was in a hurry to find a DEM geotiff that didn't belong to my company to use as an example, and I must have found the wrong type of file in my rush.

Looking at that PR discussion, it looks like the normals should work fine, so I'm probably doing something wrong on my end in Cesium. Sorry to have bothered you.
