### ISSUE TITLE
value of bounds filed  in layer.json seems to be not the file's real bounds

### ISSUE THREAD

**Issue by xiaomozi** [tum-gis/cesium-terrain-builder-docker#6]
it's bounds seems to be the follow value ,and it never change
"projection": "EPSG:4326",
  "bounds": [ 0.00, -90.00, 180.00, 90.00 ],

**Comment by BWibo** [comment]
Hey there,
this is not an issue of the Docker image but of the Cesium Terrain Builder application itself.
Get in contact with the developers of the application here: geo-data/cesium-terrain-builder#64.
